### ISSUE TITLE
Question about Composed MyCanvas dataset

### ISSUE THREAD

**Issue by cpis7** [louisYen/Gen4Gen#5]
Thank you for your great work!
I have a question about the composed MyCanvas dataset,
I understand that you segment out the subjects and compose them together, and complete background with inpainting model.
I'm wondering how the "plushie" and "bench" in composed MyCanvas can be different from the original source images? I thought they should be formed like copy & paste manner.
<img width="222" alt="image" src="https://github.com/user-attachments/assets/393b706c-fb43-4917-8868-6f4063b8e3d3">
<img width="262" alt="image" src="https://github.com/user-attachments/assets/5fb550c8-75f6-48f1-9f50-3cff99f0d568">

**Comment by danielchyeh** [comment]
Sorry for the confusion, we use several source images of a concept (e.g., images of same cat in different views) as input to our Gen4Gen. In practice, we randomly select one source image as input for each composed image.

In the Figure 1 of our paper, we have one representative of each concept for better visualization.
